#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

#dotnet-format
STAGED_CS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.cs$' || true)

 

if [ ! -z "$STAGED_CS_FILES" ]; then
  echo "Formateando archivos .cs staged..."
  echo "$STAGED_CS_FILES" | tr '\n' ' ' | xargs -r dotnet format --include
else
  echo "No hay archivos .cs para formatear"
fi


